// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQPMzG6yCfGb5WlYcqlWQHxUM6iwwnrxQ',
    appId: '1:67425296454:web:24a954f5d22163ea572a47',
    messagingSenderId: '67425296454',
    projectId: 'chatwizzi',
    authDomain: 'chatwizzi.firebaseapp.com',
    storageBucket: 'chatwizzi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU2yWHiBvRH6fYHbqGiZzj_tQrod18gXk',
    appId: '1:67425296454:android:a0bcfb2c83737bbd572a47',
    messagingSenderId: '67425296454',
    projectId: 'chatwizzi',
    storageBucket: 'chatwizzi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWIv4T9QPXusb-E6YH8r2RKaD6b7AJNDE',
    appId: '1:67425296454:ios:d73defa21bebf203572a47',
    messagingSenderId: '67425296454',
    projectId: 'chatwizzi',
    storageBucket: 'chatwizzi.appspot.com',
    androidClientId: '67425296454-b3ogeu7ddrv8i8h8ehhf5534kgq9pg7u.apps.googleusercontent.com',
    iosClientId: '67425296454-krqb2cq58hicl3vkmpjs5hb9ptsavukk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayanchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWIv4T9QPXusb-E6YH8r2RKaD6b7AJNDE',
    appId: '1:67425296454:ios:d73defa21bebf203572a47',
    messagingSenderId: '67425296454',
    projectId: 'chatwizzi',
    storageBucket: 'chatwizzi.appspot.com',
    androidClientId: '67425296454-b3ogeu7ddrv8i8h8ehhf5534kgq9pg7u.apps.googleusercontent.com',
    iosClientId: '67425296454-krqb2cq58hicl3vkmpjs5hb9ptsavukk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayanchat',
  );
}
